import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHead, Card, Stat, Badge } from '../components/ui.jsx'
import { QUOTES } from '../data/seed.js'
import { listQuotes } from '../lib/api.js'
import { IconFile, IconCube, IconWhatsApp, IconDownload, IconWallet, IconCheck } from '../components/icons.jsx'

const GHS = (n) => '₵' + Number(n).toLocaleString('en-GH', { maximumFractionDigits: 0 })

export default function Quotations() {
  // live quotes from the API, seed data as fallback if the backend is down
  const [quotes, setQuotes] = useState(QUOTES)
  const [live, setLive] = useState(false)
  useEffect(() => {
    listQuotes().then(qs => {
      if (qs.length) {
        setQuotes([...qs].reverse().map(q => ({
          id: q.quote_number, client: q.client_name, product: q.product,
          total: GHS(q.total), status: q.status, date: '—',
        })))
        setLive(true)
      }
    }).catch(() => {})
  }, [])

  return (
    <>
      <PageHead title="Quotations" subtitle="Estimates generated by the configurator and sent to clients.">
        {live && <span className="badge b-green"><span className="bdot"/>Live · from database</span>}
        <Link to="/configurator" className="btn btn-gold"><IconCube/> New Quote</Link>
      </PageHead>

      <div className="grid g-4 mb">
        <Stat label="Open Quotations" value="19" trend="8 pending reply" dir="flat" tone="orange" icon={<IconFile/>} />
        <Stat label="Value Quoted (Month)" value="₵1.24M" trend="+22%" dir="up" tone="blue" icon={<IconWallet/>} />
        <Stat label="Approved" value="11" trend="₵486K won" dir="up" tone="green" icon={<IconCheck/>} />
        <Stat label="Avg. Response Time" value="1.8 days" trend="↓ 0.4d" dir="up" tone="purple" icon={<IconFile/>} />
      </div>

      <Card title="All Quotations" pad={false}
        action={<div className="flex gap-sm"><span className="chip on">All</span><span className="chip">Sent</span><span className="chip">Approved</span><span className="chip">Draft</span></div>}>
        <div className="tbl-wrap">
          <table className="tbl">
            <thead><tr><th>Quote No.</th><th>Client</th><th>Product</th><th>Total</th><th>Status</th><th>Date</th><th></th></tr></thead>
            <tbody>
              {quotes.map(q => (
                <tr key={q.id}>
                  <td className="t-mono">{q.id}</td>
                  <td className="t-strong">{q.client}</td>
                  <td className="t-muted">{q.product}</td>
                  <td className="t-mono">{q.total}</td>
                  <td><Badge>{q.status}</Badge></td>
                  <td className="t-muted">{q.date}</td>
                  <td className="right">
                    <div className="flex gap-sm" style={{ justifyContent:'flex-end' }}>
                      <button className="btn btn-ghost btn-sm" title="Download PDF"><IconDownload style={{width:15,height:15}}/></button>
                      <button className="btn btn-ghost btn-sm" style={{color:'#25D366'}} title="Send on WhatsApp"><IconWhatsApp style={{width:15,height:15}}/></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </>
  )
}
